### ISSUE TITLE
FYI/Crash

### ISSUE THREAD

**Issue by Nexusdog** [primetoxinz/Caravans#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  LoadingPlugin (Quark-r1.2-101.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.2.0.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/20/17 3:56 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at primetoxinz.caravans.api.CaravanAPI.getRandomCaravan(CaravanAPI.java:46)
	at primetoxinz.caravans.CaravansMod.onWorldTick(CaravansMod.java:153)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_CaravansMod_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 431215624 bytes (411 MB) / 3618418688 bytes (3450 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.40 Powered by Forge 14.21.1.2415 104 mods loaded, 104 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAA	forge{14.21.1.2415} [Minecraft Forge] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.2.0} [Backpacks!] (zz-backpacks 1.12 - 3.2.0.jar) 
	UCHIJAAAA	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCHIJAAAA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.6 mc1.12.jar) 
	UCHIJAAAA	quark{r1.2-101} [Quark] (Quark-r1.2-101.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHIJAAAA	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCHIJAAAA	crafttweaker{4.0.1} [CraftTweaker2] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	caravans{{version}} [Caravans] (Caravans-0.1.2-1.12.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.8.3 mc1.12.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UCHIJAAAA	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCHIJAAAA	cyclicmagic{1.6.1} [Cyclic] (Cyclic-1.12-1.6.1.jar) 
	UCHIJAAAA	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCHIJAAAA	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCHIJAAAA	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCHIJAAAA	movingworld{1.12-4.340} [Moving World] (movingworld-1.12-4.340-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-4.334-full.jar) 
	UCHIJAAAA	dsurround{3.4.6.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHIJAAAA	presets{3.4.6.0} [§3Presets!] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHIJAAAA	eim{1.0} [eim] (EIM-1.0.0.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	csb_ench_table{1.1.2-beta2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2-beta2.jar) 
	UCHIJAAAA	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCHIJAAAA	everlastingabilities{1.3.1} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.1.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UCHIJAAAA	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCHIJAAAA	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCHIJAAAA	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCHIJAAAA	funores{1.5.5} [Fun Ores] (FunOres-1.12-1.5.5-113.jar) 
	UCHIJAAAA	gamestages{1.0.12} [Game Stages] (GameStages-1.12-1.0.12.jar) 
	UCHIJAAAA	goodluckskeleton{1.0} [Good Luck Skeleton] (goodluckskeleton-1.1-MC1.12.jar) 
	UCHIJAAAA	gravestone{1.0.11} [Gravestone] (GraveStone-1.12-Graves-1.0.11.jar) 
	UCHIJAAAA	igcm{1.0.0} [InGameConfigManager] (IGCM v1.2.0 pre-1 mc1.12.jar) 
	UCHIJAAAA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	kleeslabs{5.3.2} [KleeSlabs] (KleeSlabs_1.12-5.3.2.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.3-1.12.jar) 
	UCHIJAAAA	limelib{1.7.4} [LimeLib] (limelib-1.12-1.7.4.jar) 
	UCHIJAAAA	malisiscore{1.12-6.0.1} [MalisisCore] (malisiscore-1.12-6.0.1.jar) 
	UCHIJAAAA	malisisblocks{1.12-6.0.0} [Malisis Blocks] (malisisblocks-1.12-6.0.0.jar) 
	UCHIJAAAA	malisisdoors{1.12-7.0.2} [MalisisDoors] (malisisdoors-1.12-7.0.2.jar) 
	UCHIJAAAA	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	mendingfix{1.0.1} [Mending Fix] (mendingfix-1.0.1.jar) 
	UCHIJAAAA	minecolonies{1.12-0.8.3167} [MineColonies] (minecolonies-universal-1.12-0.8.3167.jar) 
	UCHIJAAAA	minemenu{1.6.1} [MineMenu] (MineMenu-1.12-1.6.1-universal.jar) 
	UCHIJAAAA	minions{2.0.2} [Minions] (Minions-1.12.jar) 
	UCHIJAAAA	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCHIJAAAA	mobends{0.23.4} [Mo' Bends] (mobends-0.23.4_for_MC-1.12.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCHIJAAAA	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCHIJAAAA	ob_stuff{1.1} [MSU: OpenBlocks Stuff] (MSU-OpenBlocks Stuff-1.1.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	packingtape{0.7.4} [Packing Tape] (PackingTape-1.12.0-0.7.4.jar) 
	UCHIJAAAA	harvestcraft{1.11.2i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCHIJAAAA	reccomplex{1.4.4} [Recurrent Complex] (RecurrentComplex-1.4.4.jar) 
	UCHIJAAAA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJAAAA	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCHIJAAAA	icc{0.2.1} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.1.jar) 
	UCHIJAAAA	simplebedding{1.1.0} [Simple Bedding] (simplebedding-1.1.0.jar) 
	UCHIJAAAA	simplemagnet{1.12.0-1.2.6} [Simple Magnet] (simplemagnet-1.12.0-1.2.6.jar) 
	UCHIJAAAA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCHIJAAAA	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHIJAAAA	sounds_extended{1.8.2-1.12} [Sounds Extended] (sounds extended-1.8.2-1.12.jar) 
	UCHIJAAAA	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCHIJAAAA	thut_wearables{3.0.4} [Thut's Wearables] (thut_wearables-3.0.4.jar) 
	UCHIJAAAA	thutcore{5.5.0} [Thut Core] (thutcore-5.5.0.jar) 
	UCHIJAAAA	thut_bling{2.0.0} [Thut's Bling] (thut_bling-2.0.0.d.jar) 
	UCHIJAAAA	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCHIJAAAA	tombstone{1.2.8} [Corail Tombstone] (tombstone-1.2.8-1.12.0.jar) 
	UCHIJAAAA	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCHIJAAAA	bspkrscore{at_0.9} [bspkrsCore] (Treecapitator-1.12-at_0.9a.jar) 
	UCHIJAAAA	treecapitator{at_0.9} [Treecapitator] (Treecapitator-1.12-at_0.9a.jar) 
	UCHIJAAAA	uncrafted{3.0.0pre2} [Uncrafted Mod] (Uncrafted 1.12 (v.3.0.0pre2).jar) 
	UCHIJAAAA	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCHIJAAAA	vctweaker{@MOD_VERSION@} [ViesCraft Tweaker] (ViesCraftTweaker-1.12-2.0.6.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.8.3 mc1.12.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
LoadingPlugin (Quark-r1.2-101.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ViesCraftTweakerCore (ViesCraftTweaker-1.12-2.0.6.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
BCModPlugin (zz-backpacks 1.12 - 3.2.0.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['nexusdog'/169, l='1.12. Test', x=239.62, y=66.18, z=-123.02]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by primetoxinz** [comment]
Fix in 0.1.6, on curse soon.
