### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NicosaurusRex99** [primetoxinz/Caravans#6]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/21/17 4:03 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at primetoxinz.caravans.api.CaravanAPI.getRandomCaravan(CaravanAPI.java:46)
	at primetoxinz.caravans.CaravansMod.onWorldTick(CaravansMod.java:153)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_CaravansMod_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:272)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:770)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1344733048 bytes (1282 MB) / 3325034496 bytes (3171 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2419 Optifine OptiFine_1.12_HD_U_C4 97 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2419.jar) 
	UCHIJAAAA	forge{14.21.1.2419} [Minecraft Forge] (forge-1.12-14.21.1.2419.jar) 
	UCHIJAAAA	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCHIJAAAA	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJAAAA	aromabackup{2.1.0.0.b71} [AromaBackup] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	aromabackuprecovery{2.1.0.0.b71} [AromaBackuprecovery] (AromaBackup-1.12-2.1.0.0.b71.jar) 
	UCHIJAAAA	autoplant{1.12-1.0.0} [AutoPlant] (autoplant-1.12-1.0.0.jar) 
	UCHIJAAAA	psi{r1.1-52} [Psi] (Psi-r1.1-52.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCHIJAAAA	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCHIJAAAA	bouncing_balls{1.5.1} [Bouncing Balls] (BouncingBalls-1.12-1.5.1.jar) 
	UCHIJAAAA	campfire{1.1} [Simple Camp Fire] (campfire-1.12-v1.1.jar) 
	UCHIJAAAA	crafttweaker{4.0.1} [CraftTweaker2] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	caravans{{version}} [Caravans] (Caravans-0.1.2-1.12.jar) 
	UCHIJAAAA	cavern{1.9.4} [Cavern] (Cavern_1.12-v1.9.4.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCHIJAAAA	claybucket{1.0} [Clay Bucket] (ClayBucket-1.12-1.0.jar) 
	UCHIJAAAA	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCHIJAAAA	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.10-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJAAAA	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHIJAAAA	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UCHIJAAAA	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCHIJAAAA	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UCHIJAAAA	deepresonance{1.4.9} [DeepResonance] (deepresonance-1.12-1.4.9.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.12-2.4.0.119-universal.jar) 
	UCHIJAAAA	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.9-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.13-universal.jar) 
	UCHIJAAAA	exchangers{1.12-2.2} [Exchangers] (Exchangers-1.12-2.2.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHIJAAAA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJAAAA	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.3-1.12-law.jar) 
	UCHIJAAAA	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCHIJAAAA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.12-alpha-0.0.1.jar) 
	UCHIJAAAA	grapplemod{1.12-v10} [Grappling hook mod] (grapplemod-1.12-v10.jar) 
	UCHIJAAAA	gravestone{1.0.11} [Gravestone] (GraveStone-1.12-Graves-1.0.11.jar) 
	UCHIJAAAA	hammercore{1.9.3.6} [Hammer Core] (HammerCore-1.12-1.9.3.6.jar) 
	UCHIJAAAA	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCHIJAAAA	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar) 
	UCHIJAAAA	immersiveengineering{0.12-67} [Immersive Engineering] (ImmersiveEngineering-0.12-67.jar) 
	UCHIJAAAA	immersivepetroleum{1.0.12} [Immersive Petroleum] (immersivepetroleum-1.12-1.0.12.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.12-1.3.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	jeresources{0.8.3.23} [Just Enough Resources] (JustEnoughResources-1.12-0.8.3.23.jar) 
	UCHIJAAAA	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.12.jar) 
	UCHIJAAAA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJAAAA	neat{1.4-15} [Neat] (Neat 1.4-15.jar) 
	UCHIJAAAA	nex{2.1.7.8} [NetherEx] (NetherEx-1.12-2.1.7.8.jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCHIJAAAA	harvestcraft{1.11.2i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN.jar) 
	UCHIJAAAA	reborncore{3.2.5.88} [Reborn Core] (RebornCore-1.12-3.2.5.88-universal.jar) 
	UCHIJAAAA	quantumstorage{4.3.5} [QuantumStorage] (QuantumStorage-1.12-4.3.5.jar) 
	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJAAAA	rainboaks{1.0.4-beta2} [Rainbow Oak Trees] (RainbowOaks-1.12-1.0.4-beta2.jar) 
	UCHIJAAAA	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCHIJAAAA	redstonearsenal{2.3.3} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHIJAAAA	refinedstorage{1.5.13} [Refined Storage] (refinedstorage-1.5.13.jar) 
	UCHIJAAAA	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCHIJAAAA	rflux{0.1.1} [RF Lux] (rflux-1.12-0.1.1.jar) 
	UCHIJAAAA	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCHIJAAAA	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCHIJAAAA	simplecorn{2.3.2} [Simple Corn] (SimpleCorn1.12-2.3.2.jar) 
	UCHIJAAAA	simplytea{1.4} [Simply Tea] (simplytea-1.4.jar) 
	UCHIJAAAA	solarfluxreborn{3.25r} [Solar Flux Reborn] (SolarFluxReborn_1.12-3.25r.jar) 
	UCHIJAAAA	spikemod{1.12-2.0.0} [Spike Mod] (spikemod-1.12-2.0.0.jar) 
	UCHIJAAAA	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.5.29.jar) 
	UCHIJAAAA	stg{1.12-1.2.0} [SwingThroughGrass] (stg-1.12-1.2.0.jar) 
	UCHIJAAAA	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCHIJAAAA	topaddons{1.12-0.15.0} [TOP Addons] (topaddons-1.12-0.15.0.jar) 
	UCHIJAAAA	treechopper{1.2.1} [Tree Chopper] (TreeChopper-1.12-1.2.1.jar) 
	UCHIJAAAA	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCHIJAAAA	veinminer{0.36.0} [Vein Miner] (VeinMiner-1.12-0.36.0.623+cd640ee.jar) 
	UCHIJAAAA	veinminermodsupport{0.36.0} [Mod Support] (VeinMiner-1.12-0.36.0.623+cd640ee.jar) 
	UCHIJAAAA	waddles{0.5.3} [Waddles] (Waddles-1.12-0.5.3.jar) 
	UCHIJAAAA	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['NicosaurusRex99'/226, l='world', x=265.02, y=71.00, z=26.99]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0 - Build 8.15.10.2712
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by primetoxinz** [comment]
Do you have any caravans added through crafttweaker?

**Comment by primetoxinz** [comment]
Is fixed in 0.1.6, will be on curse soon.

**Comment by NicosaurusRex99** [comment]
i havent added anything, i just installed the base version

**Comment by primetoxinz** [comment]
Yeah, the latest version on curse fixes that issue.

**Comment by NicosaurusRex99** [comment]
Cool ill add it back to my LP
